### ISSUE TITLE
Update dependencies for eslint v9 support

### ISSUE THREAD

**Issue by ahocevar** [openlayers/eslint-config-openlayers#107]
* ~~eslint-plugin-react: https://github.com/jsx-eslint/eslint-plugin-react/pull/3727~~
* eslint-plugin-import: https://github.com/import-js/eslint-plugin-import/pull/2996

**Comment by tschaub** [comment]
We could also drop the react config.

**Comment by ahocevar** [comment]
Fine with me. Should I create a pull request?

**Comment by ahocevar** [comment]
I just found that `eslint-plugin-import` also does not support eslint v9 yet. So I guess we still have to wait.

**Comment by tschaub** [comment]
> Fine with me. Should I create a pull request?

https://github.com/openlayers/eslint-config-openlayers/pull/112
