### ISSUE TITLE
Issues with setting it up

### ISSUE THREAD

**Issue by nick-gibb** [openlayers/eslint-config-openlayers#12]
Thanks for the openlayers eslint plugin. However, I'm getting an error...

In the terminal I issued this command:
```
npm install eslint eslint-config-openlayers --save-dev
```

Then I editted the .eslintrc.json file:
```
{
"extends": [
    "openlayers",
    "airbnb-base"
],
"env": {
    "browser": true,
    "commonjs": true,
    "es6": true,
    "jquery": true
}
}
```
Yet, I'm still getting errors from ESLint related to OpenLayers. For instance,
```
'ol' is not defined. (no-undef)
```

Any idea? Did I miss something? Thanks :)

**Comment by tschaub** [comment]
It sounds like you may be using the "legacy" build of OpenLayers.  This should not be used in production and cannot be used together with these linter rules.  Instead, these linter rules are meant to be used with code that looks like this:
```js
import Map from 'ol/Map';
import View from 'ol/View';
import TileLayer from 'ol/layer/Tile';
import XYZ from 'ol/source/XYZ';

new Map({
  target: 'map',
  layers: [
    new TileLayer({
      source: new XYZ({
        url: 'https://{a-c}.tile.openstreetmap.org/{z}/{x}/{y}.png'
      })
    })
  ],
  view: new View({
    center: [0, 0],
    zoom: 2
  })
});
```

See the getting started section of the [OpenLayers readme](https://github.com/openlayers/openlayers#getting-started) for more.
