### ISSUE TITLE
 'object-curly-spacing': 'error' and 'array-bracket-spacing', 'error'

### ISSUE THREAD

**Issue by fleur** [openlayers/eslint-config-openlayers#15]
Hello,

How important are these particular rules considered?  I ask because they preclude standard ES6 syntax, e.g neither of these are allowed:
```
import { fromLonLat } from 'ol/proj';
new Map({ layers: [ layer ] });
```
If I were to create a pull request to change them, would it be considered?

thanks,
fleur

**Comment by tschaub** [comment]
For posterity, the code above could be written like this:
```js
import {fromLonLat} from 'ol/proj';
new Map({layers: [layer]});
```
